apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: 1.16.0hel

dependencies:
  - name: keycloak
    version: 15.1.0
    repository: https://codecentric.github.io/helm-charts  
